package com.example.smartfarmapp;

import java.util.Date;

/**
 * --- DATA CLASS EXPLANATION ---
 * This is a "data class" (also known as a POJO - Plain Old Java Object).
 * Its only job is to hold data. It doesn't perform any actions or logic itself.
 * This `History` class represents a single snapshot of your farm's state, which is saved in the `FarmHistory` table in your database.
 * Each private variable here corresponds to a column in that table.
 */
public class History {

    // --- MEMBER VARIABLES / FIELDS ---
    // These variables store the data for a single history entry.

    private Long id; // A unique identifier for this history record, generated by the database.
    private Long farmId; // The ID of the farm this history record belongs to. This links the history to a specific farm.
    private Long temperature; // The temperature reading at the time of recording.
    private Long groundHumidity; // The ground humidity reading.
    private Long airHumidity; // The air humidity reading.
    private String pictureUrl; // A field to store a URL or reference to a picture (currently used for vegetation ID).
    private String notes; // Any notes the user or the system adds to this record.
    private Date recordedAt; // The exact date and time when this record was created.

    /**
     * --- CONSTRUCTORS ---
     * Constructors are special methods used to create new instances of a class.
     */

    /**
     * A required no-argument constructor.
     * Libraries like Gson need this to be able to create an empty `History` object before filling it with data from a JSON string.
     */
    public History() {}

    /**
     * A convenience constructor to make it easier to create a new `History` object from your code.
     * It automatically sets the current date and time and initializes notes and pictureUrl.
     * @param farmId The ID of the farm.
     * @param temperature The current temperature.
     * @param groundHumidity The current ground humidity.
     * @param airHumidity The current air humidity.
     */
    public History(Long farmId, Long temperature, Long groundHumidity, Long airHumidity) {
        this.farmId = farmId;
        this.temperature = temperature;
        this.groundHumidity = groundHumidity;
        this.airHumidity = airHumidity;
        this.recordedAt = new Date(); // Automatically sets the recording time to now.
        this.pictureUrl = ""; // Initializes as an empty string.
        this.notes = ""; // Initializes as an empty string.
    }

    /**
     * --- GETTERS AND SETTERS ---
     * These are public methods that allow other parts of your app to safely access and modify the private variables of this object.
     * This is a core principle of encapsulation - keeping the internal state of an object private and controlling access to it.
     */

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Long getFarmId() { return farmId; }
    public void setFarmId(Long farmId) { this.farmId = farmId; }

    public Long getTemperature() { return temperature; }
    public void setTemperature(Long temperature) { this.temperature = temperature; }

    public Long getGroundHumidity() { return groundHumidity; }
    public void setGroundHumidity(Long groundHumidity) { this.groundHumidity = groundHumidity; }

    public Long getAirHumidity() { return airHumidity; }
    public void setAirHumidity(Long airHumidity) { this.airHumidity = airHumidity; }

    public String getPictureUrl() { return pictureUrl; }
    public void setPictureUrl(String pictureUrl) { this.pictureUrl = pictureUrl; }

    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }

    public Date getRecordedAt() { return recordedAt; }
    public void setRecordedAt(Date recordedAt) { this.recordedAt = recordedAt; }
}
